// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package Db

import (
	"database/sql"
)

type Profile struct {
	ID        int64
	UserID    sql.NullInt64
	AvatarUrl sql.NullString
	Bio       sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        int64
	Email     string
	Name      string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
