// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package Db

import (
	"context"
)

const getUserByIdNew = `-- name: GetUserByIdNew :one
select id, name, email, created_at from users where id=$1
`

func (q *Queries) GetUserByIdNew(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByIdNew, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
